//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBSecurity
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginInfo", Namespace="http://schemas.datacontract.org/2004/07/ExternalBankingSecurityLibrary")]
    public partial class LoginInfo : object
    {
        
        private System.Collections.Generic.Dictionary<string, string> AdditionalDetailsField;
        
        private bool ForUnlockingField;
        
        private string IpAddressField;
        
        private string OTPField;
        
        private string PasswordField;
        
        private XBSecurity.PlatformType PlatformTypeField;
        
        private string TokenIdField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> AdditionalDetails
        {
            get
            {
                return this.AdditionalDetailsField;
            }
            set
            {
                this.AdditionalDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ForUnlocking
        {
            get
            {
                return this.ForUnlockingField;
            }
            set
            {
                this.ForUnlockingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IpAddress
        {
            get
            {
                return this.IpAddressField;
            }
            set
            {
                this.IpAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OTP
        {
            get
            {
                return this.OTPField;
            }
            set
            {
                this.OTPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public XBSecurity.PlatformType PlatformType
        {
            get
            {
                return this.PlatformTypeField;
            }
            set
            {
                this.PlatformTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenId
        {
            get
            {
                return this.TokenIdField;
            }
            set
            {
                this.TokenIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlatformType", Namespace="http://schemas.datacontract.org/2004/07/ExternalBankingSecurityLibrary")]
    public enum PlatformType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OnlineBanking = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MobileBanking = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExternalUser", Namespace="http://schemas.datacontract.org/2004/07/ExternalBankingSecurityLibrary")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(XBSecurity.OnlineBankingUser))]
    public partial class ExternalUser : object
    {
        
        private int BranchCodeField;
        
        private int ChangeRequirementField;
        
        private string CustomerNumberField;
        
        private string FullNameField;
        
        private string FullNameEngField;
        
        private int PermissionField;
        
        private string SessionIDField;
        
        private int UserIDField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BranchCode
        {
            get
            {
                return this.BranchCodeField;
            }
            set
            {
                this.BranchCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChangeRequirement
        {
            get
            {
                return this.ChangeRequirementField;
            }
            set
            {
                this.ChangeRequirementField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerNumber
        {
            get
            {
                return this.CustomerNumberField;
            }
            set
            {
                this.CustomerNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullNameEng
        {
            get
            {
                return this.FullNameEngField;
            }
            set
            {
                this.FullNameEngField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Permission
        {
            get
            {
                return this.PermissionField;
            }
            set
            {
                this.PermissionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionID
        {
            get
            {
                return this.SessionIDField;
            }
            set
            {
                this.SessionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OnlineBankingUser", Namespace="http://schemas.datacontract.org/2004/07/ExternalBankingSecurityLibrary")]
    public partial class OnlineBankingUser : XBSecurity.ExternalUser
    {
        
        private int AllowDataEntryField;
        
        private int ApprovementSchemeField;
        
        private XBSecurity.LoginResult AuthorizationResultField;
        
        private double DailyTransactionsLimitField;
        
        private int GoodLogonsField;
        
        private bool IsLastConfirmerField;
        
        private int LimitedAccessField;
        
        private double OneTransactionLimitField;
        
        private XBSecurity.ChangePasswordResult PasswordChangeResultField;
        
        private int SecondConfirmField;
        
        private int TypeOfClientField;
        
        private System.Collections.Generic.List<XBSecurity.UserGroup> UserGroupsField;
        
        private XBSecurity.UserSecurityInfo UserSecurityInformationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AllowDataEntry
        {
            get
            {
                return this.AllowDataEntryField;
            }
            set
            {
                this.AllowDataEntryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ApprovementScheme
        {
            get
            {
                return this.ApprovementSchemeField;
            }
            set
            {
                this.ApprovementSchemeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public XBSecurity.LoginResult AuthorizationResult
        {
            get
            {
                return this.AuthorizationResultField;
            }
            set
            {
                this.AuthorizationResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double DailyTransactionsLimit
        {
            get
            {
                return this.DailyTransactionsLimitField;
            }
            set
            {
                this.DailyTransactionsLimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GoodLogons
        {
            get
            {
                return this.GoodLogonsField;
            }
            set
            {
                this.GoodLogonsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLastConfirmer
        {
            get
            {
                return this.IsLastConfirmerField;
            }
            set
            {
                this.IsLastConfirmerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LimitedAccess
        {
            get
            {
                return this.LimitedAccessField;
            }
            set
            {
                this.LimitedAccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double OneTransactionLimit
        {
            get
            {
                return this.OneTransactionLimitField;
            }
            set
            {
                this.OneTransactionLimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public XBSecurity.ChangePasswordResult PasswordChangeResult
        {
            get
            {
                return this.PasswordChangeResultField;
            }
            set
            {
                this.PasswordChangeResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SecondConfirm
        {
            get
            {
                return this.SecondConfirmField;
            }
            set
            {
                this.SecondConfirmField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypeOfClient
        {
            get
            {
                return this.TypeOfClientField;
            }
            set
            {
                this.TypeOfClientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<XBSecurity.UserGroup> UserGroups
        {
            get
            {
                return this.UserGroupsField;
            }
            set
            {
                this.UserGroupsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public XBSecurity.UserSecurityInfo UserSecurityInformation
        {
            get
            {
                return this.UserSecurityInformationField;
            }
            set
            {
                this.UserSecurityInformationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResult", Namespace="http://schemas.datacontract.org/2004/07/ExternalBankingSecurityLibrary")]
    public partial class LoginResult : object
    {
        
        private string DescriptionField;
        
        private string DescriptionAMField;
        
        private bool IsAuthorizedField;
        
        private XBSecurity.LoginResultCode ResultCodeField;
        
        private System.Guid SessionIDField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescriptionAM
        {
            get
            {
                return this.DescriptionAMField;
            }
            set
            {
                this.DescriptionAMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAuthorized
        {
            get
            {
                return this.IsAuthorizedField;
            }
            set
            {
                this.IsAuthorizedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public XBSecurity.LoginResultCode ResultCode
        {
            get
            {
                return this.ResultCodeField;
            }
            set
            {
                this.ResultCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SessionID
        {
            get
            {
                return this.SessionIDField;
            }
            set
            {
                this.SessionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangePasswordResult", Namespace="http://schemas.datacontract.org/2004/07/ExternalBankingSecurityLibrary")]
    public partial class ChangePasswordResult : object
    {
        
        private string DescriptionField;
        
        private string DescriptionAMField;
        
        private bool IsChangedField;
        
        private int ResultCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescriptionAM
        {
            get
            {
                return this.DescriptionAMField;
            }
            set
            {
                this.DescriptionAMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsChanged
        {
            get
            {
                return this.IsChangedField;
            }
            set
            {
                this.IsChangedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResultCode
        {
            get
            {
                return this.ResultCodeField;
            }
            set
            {
                this.ResultCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserSecurityInfo", Namespace="http://schemas.datacontract.org/2004/07/ExternalBankingSecurityLibrary")]
    public partial class UserSecurityInfo : object
    {
        
        private string BadIPField;
        
        private int BadLogonsField;
        
        private double DailyTransactionsLimitField;
        
        private System.DateTime DateOfRegistrationField;
        
        private string GoodIPField;
        
        private int GoodLogonsField;
        
        private int IDField;
        
        private System.DateTime LastBadLogonDateField;
        
        private System.DateTime LastGoodLogonDateField;
        
        private double OneTransactionLimitField;
        
        private System.DateTime PasswordChangeDateField;
        
        private int PermissionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BadIP
        {
            get
            {
                return this.BadIPField;
            }
            set
            {
                this.BadIPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BadLogons
        {
            get
            {
                return this.BadLogonsField;
            }
            set
            {
                this.BadLogonsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double DailyTransactionsLimit
        {
            get
            {
                return this.DailyTransactionsLimitField;
            }
            set
            {
                this.DailyTransactionsLimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfRegistration
        {
            get
            {
                return this.DateOfRegistrationField;
            }
            set
            {
                this.DateOfRegistrationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GoodIP
        {
            get
            {
                return this.GoodIPField;
            }
            set
            {
                this.GoodIPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GoodLogons
        {
            get
            {
                return this.GoodLogonsField;
            }
            set
            {
                this.GoodLogonsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastBadLogonDate
        {
            get
            {
                return this.LastBadLogonDateField;
            }
            set
            {
                this.LastBadLogonDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastGoodLogonDate
        {
            get
            {
                return this.LastGoodLogonDateField;
            }
            set
            {
                this.LastGoodLogonDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double OneTransactionLimit
        {
            get
            {
                return this.OneTransactionLimitField;
            }
            set
            {
                this.OneTransactionLimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PasswordChangeDate
        {
            get
            {
                return this.PasswordChangeDateField;
            }
            set
            {
                this.PasswordChangeDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Permission
        {
            get
            {
                return this.PermissionField;
            }
            set
            {
                this.PermissionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserGroup", Namespace="http://schemas.datacontract.org/2004/07/ExternalBankingSecurityLibrary")]
    public partial class UserGroup : object
    {
        
        private int GroupIDField;
        
        private string GroupNameField;
        
        private int GroupNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroupID
        {
            get
            {
                return this.GroupIDField;
            }
            set
            {
                this.GroupIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName
        {
            get
            {
                return this.GroupNameField;
            }
            set
            {
                this.GroupNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroupNumber
        {
            get
            {
                return this.GroupNumberField;
            }
            set
            {
                this.GroupNumberField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResultCode", Namespace="http://schemas.datacontract.org/2004/07/ExternalBankingSecurityLibrary")]
    public enum LoginResultCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChangePassword = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerificationFailed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OtherError = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CorrectLogin = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataNotVerified = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmptyData = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EnterenceDenied = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Locked15min = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthorizationObjectNotFoundInCache = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthorizationObjectCanNotBeNull = 9,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangePasswordInfo", Namespace="http://schemas.datacontract.org/2004/07/ExternalBankingSecurityLibrary")]
    public partial class ChangePasswordInfo : object
    {
        
        private string IpAddressField;
        
        private string NewPasswordField;
        
        private string PasswordField;
        
        private string RetypePasswordField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IpAddress
        {
            get
            {
                return this.IpAddressField;
            }
            set
            {
                this.IpAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewPassword
        {
            get
            {
                return this.NewPasswordField;
            }
            set
            {
                this.NewPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RetypePassword
        {
            get
            {
                return this.RetypePasswordField;
            }
            set
            {
                this.RetypePasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="XBSecurity.IOnlineBankingSecurityCas")]
    public interface IOnlineBankingSecurityCas
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBankingSecurityCas/AuthorizeUser", ReplyAction="http://tempuri.org/IOnlineBankingSecurityCas/AuthorizeUserResponse")]
        System.Threading.Tasks.Task<XBSecurity.OnlineBankingUser> AuthorizeUserAsync(XBSecurity.LoginInfo lInfo, byte lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBankingSecurityCas/AuthorizeUserByUserPassword", ReplyAction="http://tempuri.org/IOnlineBankingSecurityCas/AuthorizeUserByUserPasswordResponse")]
        System.Threading.Tasks.Task<XBSecurity.OnlineBankingUser> AuthorizeUserByUserPasswordAsync(XBSecurity.LoginInfo lInfo, byte lang, string hostName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBankingSecurityCas/AuthorizeUserByToken", ReplyAction="http://tempuri.org/IOnlineBankingSecurityCas/AuthorizeUserByTokenResponse")]
        System.Threading.Tasks.Task<XBSecurity.OnlineBankingUser> AuthorizeUserByTokenAsync(XBSecurity.LoginInfo lInfo, XBSecurity.LoginResult lResult, byte lang, string hostName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBankingSecurityCas/ChangeUserPassword", ReplyAction="http://tempuri.org/IOnlineBankingSecurityCas/ChangeUserPasswordResponse")]
        System.Threading.Tasks.Task<XBSecurity.OnlineBankingUser> ChangeUserPasswordAsync(XBSecurity.ChangePasswordInfo cpInfo, string sessionID, byte lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBankingSecurityCas/CheckAuthorization", ReplyAction="http://tempuri.org/IOnlineBankingSecurityCas/CheckAuthorizationResponse")]
        System.Threading.Tasks.Task<XBSecurity.OnlineBankingUser> CheckAuthorizationAsync(string sessionID, byte lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBankingSecurityCas/SingData", ReplyAction="http://tempuri.org/IOnlineBankingSecurityCas/SingDataResponse")]
        System.Threading.Tasks.Task<bool> SingDataAsync(string sessionID, string otp, System.Collections.Generic.Dictionary<string, string> dfs, byte lang, string UserName, string IpAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBankingSecurityCas/VerifyToken", ReplyAction="http://tempuri.org/IOnlineBankingSecurityCas/VerifyTokenResponse")]
        System.Threading.Tasks.Task<bool> VerifyTokenAsync(string sessionID, string otp, string ipAddress, byte lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBankingSecurityCas/CheckRegistrationCode", ReplyAction="http://tempuri.org/IOnlineBankingSecurityCas/CheckRegistrationCodeResponse")]
        System.Threading.Tasks.Task<bool> CheckRegistrationCodeAsync(string registrationCode, string deviceTypeDescription, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBankingSecurityCas/ResetUserPassword", ReplyAction="http://tempuri.org/IOnlineBankingSecurityCas/ResetUserPasswordResponse")]
        System.Threading.Tasks.Task<bool> ResetUserPasswordAsync(XBSecurity.LoginInfo lInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBankingSecurityCas/GetTypeOfUser", ReplyAction="http://tempuri.org/IOnlineBankingSecurityCas/GetTypeOfUserResponse")]
        System.Threading.Tasks.Task<int> GetTypeOfUserAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBankingSecurityCas/LogOut", ReplyAction="http://tempuri.org/IOnlineBankingSecurityCas/LogOutResponse")]
        System.Threading.Tasks.Task LogOutAsync(string sessionId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IOnlineBankingSecurityCasChannel : XBSecurity.IOnlineBankingSecurityCas, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class OnlineBankingSecurityCasClient : System.ServiceModel.ClientBase<XBSecurity.IOnlineBankingSecurityCas>, XBSecurity.IOnlineBankingSecurityCas
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OnlineBankingSecurityCasClient(EndpointConfiguration endpointConfiguration) : 
                base(OnlineBankingSecurityCasClient.GetBindingForEndpoint(endpointConfiguration), OnlineBankingSecurityCasClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OnlineBankingSecurityCasClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OnlineBankingSecurityCasClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OnlineBankingSecurityCasClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OnlineBankingSecurityCasClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OnlineBankingSecurityCasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<XBSecurity.OnlineBankingUser> AuthorizeUserAsync(XBSecurity.LoginInfo lInfo, byte lang)
        {
            return base.Channel.AuthorizeUserAsync(lInfo, lang);
        }
        
        public System.Threading.Tasks.Task<XBSecurity.OnlineBankingUser> AuthorizeUserByUserPasswordAsync(XBSecurity.LoginInfo lInfo, byte lang, string hostName)
        {
            return base.Channel.AuthorizeUserByUserPasswordAsync(lInfo, lang, hostName);
        }
        
        public System.Threading.Tasks.Task<XBSecurity.OnlineBankingUser> AuthorizeUserByTokenAsync(XBSecurity.LoginInfo lInfo, XBSecurity.LoginResult lResult, byte lang, string hostName)
        {
            return base.Channel.AuthorizeUserByTokenAsync(lInfo, lResult, lang, hostName);
        }
        
        public System.Threading.Tasks.Task<XBSecurity.OnlineBankingUser> ChangeUserPasswordAsync(XBSecurity.ChangePasswordInfo cpInfo, string sessionID, byte lang)
        {
            return base.Channel.ChangeUserPasswordAsync(cpInfo, sessionID, lang);
        }
        
        public System.Threading.Tasks.Task<XBSecurity.OnlineBankingUser> CheckAuthorizationAsync(string sessionID, byte lang)
        {
            return base.Channel.CheckAuthorizationAsync(sessionID, lang);
        }
        
        public System.Threading.Tasks.Task<bool> SingDataAsync(string sessionID, string otp, System.Collections.Generic.Dictionary<string, string> dfs, byte lang, string UserName, string IpAddress)
        {
            return base.Channel.SingDataAsync(sessionID, otp, dfs, lang, UserName, IpAddress);
        }
        
        public System.Threading.Tasks.Task<bool> VerifyTokenAsync(string sessionID, string otp, string ipAddress, byte lang)
        {
            return base.Channel.VerifyTokenAsync(sessionID, otp, ipAddress, lang);
        }
        
        public System.Threading.Tasks.Task<bool> CheckRegistrationCodeAsync(string registrationCode, string deviceTypeDescription, string userName)
        {
            return base.Channel.CheckRegistrationCodeAsync(registrationCode, deviceTypeDescription, userName);
        }
        
        public System.Threading.Tasks.Task<bool> ResetUserPasswordAsync(XBSecurity.LoginInfo lInfo)
        {
            return base.Channel.ResetUserPasswordAsync(lInfo);
        }
        
        public System.Threading.Tasks.Task<int> GetTypeOfUserAsync(string userName)
        {
            return base.Channel.GetTypeOfUserAsync(userName);
        }
        
        public System.Threading.Tasks.Task LogOutAsync(string sessionId)
        {
            return base.Channel.LogOutAsync(sessionId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IOnlineBankingSecurityCas))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IOnlineBankingSecurityCas))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IOnlineBankingSecurityCas))
            {
                return new System.ServiceModel.EndpointAddress("https://xbsecurity-dev:4443/Services/OnlineBankingSecurityCas.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IOnlineBankingSecurityCas))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://as1001-d.acbaca.local:9080/Services/OnlineBankingSecurityCas.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpsBinding_IOnlineBankingSecurityCas,
            
            NetTcpBinding_IOnlineBankingSecurityCas,
        }
    }
}
