//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSMessagingServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/MessagingLibrary.Services.SMSMessagingSer" +
        "vice")]
    public partial class User : object
    {
        
        private short userIDField;
        
        private string userNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short userID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSMessagingSession", Namespace="http://schemas.datacontract.org/2004/07/MessagingLibrary.Services.SMSMessagingSer" +
        "vice")]
    public partial class SMSMessagingSession : object
    {
        
        private string DescriptionField;
        
        private uint IDField;
        
        private string MessagesField;
        
        private System.Collections.Generic.List<SMSMessagingServiceReference.SMSMessage> MessagesListField;
        
        private System.DateTime RegistrationDateField;
        
        private int StatusField;
        
        private string StatusDescriptionField;
        
        private int UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Messages
        {
            get
            {
                return this.MessagesField;
            }
            set
            {
                this.MessagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SMSMessagingServiceReference.SMSMessage> MessagesList
        {
            get
            {
                return this.MessagesListField;
            }
            set
            {
                this.MessagesListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegistrationDate
        {
            get
            {
                return this.RegistrationDateField;
            }
            set
            {
                this.RegistrationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDescription
        {
            get
            {
                return this.StatusDescriptionField;
            }
            set
            {
                this.StatusDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSMessage", Namespace="http://schemas.datacontract.org/2004/07/MessagingLibrary.Services.SMSMessagingSer" +
        "vice")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMSMessagingServiceReference.OneMessage))]
    public partial class SMSMessage : object
    {
        
        private ulong CustomerNumberField;
        
        private string ExternalIdField;
        
        private ulong IdentityIdField;
        
        private string MessageField;
        
        private int MessageTypeField;
        
        private string PhoneNumberField;
        
        private ushort SourceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ulong CustomerNumber
        {
            get
            {
                return this.CustomerNumberField;
            }
            set
            {
                this.CustomerNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalId
        {
            get
            {
                return this.ExternalIdField;
            }
            set
            {
                this.ExternalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ulong IdentityId
        {
            get
            {
                return this.IdentityIdField;
            }
            set
            {
                this.IdentityIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MessageType
        {
            get
            {
                return this.MessageTypeField;
            }
            set
            {
                this.MessageTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OneMessage", Namespace="http://schemas.datacontract.org/2004/07/MessagingLibrary.Services.SMSMessagingSer" +
        "vice.Models")]
    public partial class OneMessage : SMSMessagingServiceReference.SMSMessage
    {
        
        private double MessageSesionIdField;
        
        private double ProductIdField;
        
        private System.DateTime RegDateField;
        
        private int RegistrationSetNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MessageSesionId
        {
            get
            {
                return this.MessageSesionIdField;
            }
            set
            {
                this.MessageSesionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ProductId
        {
            get
            {
                return this.ProductIdField;
            }
            set
            {
                this.ProductIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegDate
        {
            get
            {
                return this.RegDateField;
            }
            set
            {
                this.RegDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RegistrationSetNumber
        {
            get
            {
                return this.RegistrationSetNumberField;
            }
            set
            {
                this.RegistrationSetNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchSMSMessagingSession", Namespace="http://schemas.datacontract.org/2004/07/MessagingLibrary.Services.SMSMessagingSer" +
        "vice")]
    public partial class SearchSMSMessagingSession : object
    {
        
        private string DescriptionField;
        
        private System.DateTime RegistrationDateField;
        
        private System.Nullable<int> StatusField;
        
        private System.Nullable<int> UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegistrationDate
        {
            get
            {
                return this.RegistrationDateField;
            }
            set
            {
                this.RegistrationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMSMessagingServiceReference.ISMSMessagingService")]
    public interface ISMSMessagingService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSMessagingService/SetCurrentUser", ReplyAction="http://tempuri.org/ISMSMessagingService/SetCurrentUserResponse")]
        System.Threading.Tasks.Task SetCurrentUserAsync(SMSMessagingServiceReference.User currentUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSMessagingService/SetClientIp", ReplyAction="http://tempuri.org/ISMSMessagingService/SetClientIpResponse")]
        System.Threading.Tasks.Task SetClientIpAsync(string clientIp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSMessagingService/SaveMessagingSession", ReplyAction="http://tempuri.org/ISMSMessagingService/SaveMessagingSessionResponse")]
        System.Threading.Tasks.Task SaveMessagingSessionAsync(SMSMessagingServiceReference.SMSMessagingSession messagingSession);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSMessagingService/ChangeSMSMessagingSessionStatus", ReplyAction="http://tempuri.org/ISMSMessagingService/ChangeSMSMessagingSessionStatusResponse")]
        System.Threading.Tasks.Task ChangeSMSMessagingSessionStatusAsync(uint id, byte newStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSMessagingService/GetSMSMessagingSessions", ReplyAction="http://tempuri.org/ISMSMessagingService/GetSMSMessagingSessionsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SMSMessagingServiceReference.SMSMessagingSession>> GetSMSMessagingSessionsAsync(SMSMessagingServiceReference.SearchSMSMessagingSession searchParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSMessagingService/DeleteMessagingSession", ReplyAction="http://tempuri.org/ISMSMessagingService/DeleteMessagingSessionResponse")]
        System.Threading.Tasks.Task DeleteMessagingSessionAsync(uint id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSMessagingService/SendMessage", ReplyAction="http://tempuri.org/ISMSMessagingService/SendMessageResponse")]
        System.Threading.Tasks.Task SendMessageAsync(string phoneNumber, ulong customerNumber, string message, int registrationSetNumber, int messageType, ushort source, string externalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSMessagingService/SendMessages", ReplyAction="http://tempuri.org/ISMSMessagingService/SendMessagesResponse")]
        System.Threading.Tasks.Task SendMessagesAsync(System.Collections.Generic.List<SMSMessagingServiceReference.SMSMessage> messages, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSMessagingService/SendOneMessage", ReplyAction="http://tempuri.org/ISMSMessagingService/SendOneMessageResponse")]
        System.Threading.Tasks.Task SendOneMessageAsync(SMSMessagingServiceReference.OneMessage message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ISMSMessagingServiceChannel : SMSMessagingServiceReference.ISMSMessagingService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SMSMessagingServiceClient : System.ServiceModel.ClientBase<SMSMessagingServiceReference.ISMSMessagingService>, SMSMessagingServiceReference.ISMSMessagingService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SMSMessagingServiceClient() : 
                base(SMSMessagingServiceClient.GetDefaultBinding(), SMSMessagingServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.MessagingService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SMSMessagingServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SMSMessagingServiceClient.GetBindingForEndpoint(endpointConfiguration), SMSMessagingServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SMSMessagingServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SMSMessagingServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SMSMessagingServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SMSMessagingServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SMSMessagingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task SetCurrentUserAsync(SMSMessagingServiceReference.User currentUser)
        {
            return base.Channel.SetCurrentUserAsync(currentUser);
        }
        
        public System.Threading.Tasks.Task SetClientIpAsync(string clientIp)
        {
            return base.Channel.SetClientIpAsync(clientIp);
        }
        
        public System.Threading.Tasks.Task SaveMessagingSessionAsync(SMSMessagingServiceReference.SMSMessagingSession messagingSession)
        {
            return base.Channel.SaveMessagingSessionAsync(messagingSession);
        }
        
        public System.Threading.Tasks.Task ChangeSMSMessagingSessionStatusAsync(uint id, byte newStatus)
        {
            return base.Channel.ChangeSMSMessagingSessionStatusAsync(id, newStatus);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SMSMessagingServiceReference.SMSMessagingSession>> GetSMSMessagingSessionsAsync(SMSMessagingServiceReference.SearchSMSMessagingSession searchParams)
        {
            return base.Channel.GetSMSMessagingSessionsAsync(searchParams);
        }
        
        public System.Threading.Tasks.Task DeleteMessagingSessionAsync(uint id)
        {
            return base.Channel.DeleteMessagingSessionAsync(id);
        }
        
        public System.Threading.Tasks.Task SendMessageAsync(string phoneNumber, ulong customerNumber, string message, int registrationSetNumber, int messageType, ushort source, string externalId)
        {
            return base.Channel.SendMessageAsync(phoneNumber, customerNumber, message, registrationSetNumber, messageType, source, externalId);
        }
        
        public System.Threading.Tasks.Task SendMessagesAsync(System.Collections.Generic.List<SMSMessagingServiceReference.SMSMessage> messages, string description)
        {
            return base.Channel.SendMessagesAsync(messages, description);
        }
        
        public System.Threading.Tasks.Task SendOneMessageAsync(SMSMessagingServiceReference.OneMessage message)
        {
            return base.Channel.SendOneMessageAsync(message);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MessagingService))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MessagingService))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://wcf1001-t.acbaca.local:8089/SMSMessagingService/SMSMessagingService.svc" +
                        "/MessagingService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SMSMessagingServiceClient.GetBindingForEndpoint(EndpointConfiguration.MessagingService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SMSMessagingServiceClient.GetEndpointAddress(EndpointConfiguration.MessagingService);
        }
        
        public enum EndpointConfiguration
        {
            
            MessagingService,
        }
    }
}
